apiVersion: apps/v1
kind: Deployment
metadata:
  name: lojas-deployment
spec:
  selector:
    matchLabels:
      app: lojas
  template:
    metadata:
      labels:
        app: lojas
    spec:
      containers:
      - name: lojas
        image: joaosantos7293/lojas
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- #med-clusterip
apiVersion: v1
kind: Service
metadata:
  name: lojas-clusterip
spec:
  selector:
    app: lojas
  ports:
    - name: lojas
      protocol: TCP
      port: 4000
      targetPort: 4000
