apiVersion: v1
kind: Service
metadata:
  name: produtos-service
spec:
  type: NodePort
  selector:
    app: produtos
  ports:
    - name: produtos
      protocol: TCP
      port: 3001
      targetPort: 3001
