apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtos-deployment
spec:
  selector:
    matchLabels:
      app: produtos
  template:
    metadata:
      labels:
        app: produtos
    spec:
      containers:
      - name: produtos
        image: joaosantos7293/pro
        resources:
          limits:
            memory: "128Mi"
            cpu: 1
--- #med-clusterip
apiVersion: v1
kind: Service
metadata:
  name: produtos-clusterip
spec:
  selector:
    app: produtos
  ports:
    - name: produtos
      protocol: TCP
      port: 3001
      targetPort: 3001
