apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  selector:
    matchLabels:
      app: produto
  template:
    metadata:
      labels:
        app: produto
    spec:
      containers:
      - name: produto
        image: joaosantos7293/prod
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
--- #usu-clusterip
apiVersion: v1
kind: Service
metadata:
  name: prod-clusterip
spec:
  selector:
    app: produto
  ports:
    - name: produto
      protocol: TCP
      port: 3001
      targetPort: 3001
