apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  type: NodePort
  selector:
    app: produto
  ports:
    - name: produto
      protocol: TCP
      port: 3001
      targetPort: 3001
